### ISSUE TITLE
 raise TesseractNotFound

### ISSUE THREAD

**Issue by WuHuaJi0** [RobinDavid/Pytesser#2]
I download this library , and import it to my program . But , when I use the function :
 `image_to_string()`
it broke by a error : 
```
Traceback (most recent call last):
  File "/home/jwc.py", line 48, in <module>
    getNum()
  File "/home/jwc.py", line 43, in getNum
    text = image_to_string(out)
  File "/home/pytesser.py", line 77, in image_to_string
    check_path() #Check if tesseract available in the path
  File "/home/pytesser.py", line 44, in check_path
    raise TesseractNotFound
pytesser.TesseractNotFound
```
i don't have idea . so i wanner  what's wrong and how to fix it ?

**Comment by RobinDavid** [comment]
The tesseract binary is not in your path. This module is just a python interface for tesseract. Is `which tesseract` showing you where it is ? If not the binary is probably not installed.

**Comment by WuHuaJi0** [comment]
Thank for you answer ，I found it need tesseact first , i installed ,then this problem solved.
